/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ScoringRouteImport } from './routes/scoring'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LessonRouteImport } from './routes/lesson'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamSessionIdRouteImport } from './routes/exam.$sessionId'
import { Route as AdminSchedulerRouteImport } from './routes/admin/scheduler'
import { Route as AdminRewardsRouteImport } from './routes/admin/rewards'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminConsoleRouteImport } from './routes/admin/console'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoringRoute = ScoringRouteImport.update({
  id: '/scoring',
  path: '/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonRoute = LessonRouteImport.update({
  id: '/lesson',
  path: '/lesson',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSessionIdRoute = ExamSessionIdRouteImport.update({
  id: '/exam/$sessionId',
  path: '/exam/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchedulerRoute = AdminSchedulerRouteImport.update({
  id: '/admin/scheduler',
  path: '/admin/scheduler',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRewardsRoute = AdminRewardsRouteImport.update({
  id: '/admin/rewards',
  path: '/admin/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleRoute = AdminConsoleRouteImport.update({
  id: '/admin/console',
  path: '/admin/console',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/billing': typeof BillingRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/lesson': typeof LessonRoute
  '/logout': typeof LogoutRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/scoring': typeof ScoringRoute
  '/student': typeof StudentRoute
  '/wallet': typeof WalletRoute
  '/admin/console': typeof AdminConsoleRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/exam/$sessionId': typeof ExamSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/billing': typeof BillingRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/lesson': typeof LessonRoute
  '/logout': typeof LogoutRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/scoring': typeof ScoringRoute
  '/student': typeof StudentRoute
  '/wallet': typeof WalletRoute
  '/admin/console': typeof AdminConsoleRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/exam/$sessionId': typeof ExamSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/billing': typeof BillingRoute
  '/callback': typeof CallbackRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/lesson': typeof LessonRoute
  '/logout': typeof LogoutRoute
  '/plan': typeof PlanRoute
  '/practice': typeof PracticeRoute
  '/scoring': typeof ScoringRoute
  '/student': typeof StudentRoute
  '/wallet': typeof WalletRoute
  '/admin/console': typeof AdminConsoleRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/rewards': typeof AdminRewardsRoute
  '/admin/scheduler': typeof AdminSchedulerRoute
  '/exam/$sessionId': typeof ExamSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/billing'
    | '/callback'
    | '/dashboard'
    | '/health'
    | '/lesson'
    | '/logout'
    | '/plan'
    | '/practice'
    | '/scoring'
    | '/student'
    | '/wallet'
    | '/admin/console'
    | '/admin/content'
    | '/admin/profile'
    | '/admin/rewards'
    | '/admin/scheduler'
    | '/exam/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/billing'
    | '/callback'
    | '/dashboard'
    | '/health'
    | '/lesson'
    | '/logout'
    | '/plan'
    | '/practice'
    | '/scoring'
    | '/student'
    | '/wallet'
    | '/admin/console'
    | '/admin/content'
    | '/admin/profile'
    | '/admin/rewards'
    | '/admin/scheduler'
    | '/exam/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/billing'
    | '/callback'
    | '/dashboard'
    | '/health'
    | '/lesson'
    | '/logout'
    | '/plan'
    | '/practice'
    | '/scoring'
    | '/student'
    | '/wallet'
    | '/admin/console'
    | '/admin/content'
    | '/admin/profile'
    | '/admin/rewards'
    | '/admin/scheduler'
    | '/exam/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BillingRoute: typeof BillingRoute
  CallbackRoute: typeof CallbackRoute
  DashboardRoute: typeof DashboardRoute
  HealthRoute: typeof HealthRoute
  LessonRoute: typeof LessonRoute
  LogoutRoute: typeof LogoutRoute
  PlanRoute: typeof PlanRoute
  PracticeRoute: typeof PracticeRoute
  ScoringRoute: typeof ScoringRoute
  StudentRoute: typeof StudentRoute
  WalletRoute: typeof WalletRoute
  AdminConsoleRoute: typeof AdminConsoleRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRewardsRoute: typeof AdminRewardsRoute
  AdminSchedulerRoute: typeof AdminSchedulerRoute
  ExamSessionIdRoute: typeof ExamSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scoring': {
      id: '/scoring'
      path: '/scoring'
      fullPath: '/scoring'
      preLoaderRoute: typeof ScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson': {
      id: '/lesson'
      path: '/lesson'
      fullPath: '/lesson'
      preLoaderRoute: typeof LessonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$sessionId': {
      id: '/exam/$sessionId'
      path: '/exam/$sessionId'
      fullPath: '/exam/$sessionId'
      preLoaderRoute: typeof ExamSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/scheduler': {
      id: '/admin/scheduler'
      path: '/admin/scheduler'
      fullPath: '/admin/scheduler'
      preLoaderRoute: typeof AdminSchedulerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rewards': {
      id: '/admin/rewards'
      path: '/admin/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AdminRewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/console': {
      id: '/admin/console'
      path: '/admin/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AdminConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BillingRoute: BillingRoute,
  CallbackRoute: CallbackRoute,
  DashboardRoute: DashboardRoute,
  HealthRoute: HealthRoute,
  LessonRoute: LessonRoute,
  LogoutRoute: LogoutRoute,
  PlanRoute: PlanRoute,
  PracticeRoute: PracticeRoute,
  ScoringRoute: ScoringRoute,
  StudentRoute: StudentRoute,
  WalletRoute: WalletRoute,
  AdminConsoleRoute: AdminConsoleRoute,
  AdminContentRoute: AdminContentRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRewardsRoute: AdminRewardsRoute,
  AdminSchedulerRoute: AdminSchedulerRoute,
  ExamSessionIdRoute: ExamSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
